### ISSUE TITLE
Security Administration Design

### ISSUE THREAD

**Issue by mdfrederick** [Masterworks/Clarity-Components#1]
[Trevor's notes in Slides](https://docs.google.com/presentation/d/1a3J9KpOK8AKMMedWFQseqPr3fLPJh_ZGHOi1iByKxQc/edit#slide=id.g3b6b32c460_0_55)
[Diagram](https://docs.google.com/drawings/d/1rDqIcTvdKq1wK-5WTfxGe_WjB4ALDljVB1_yvW8E-iI/edit)
[Rough requirements](https://docs.google.com/document/d/1XPTsAqT-kGnCcid5YfvZvDXmbVIUu-wyFxYspFi3ISU/edit)

**Comment by mdfrederick** [comment]
"Inspiration" from Salesforce administrative screens:
https://masterworks.slack.com/files/U87J9SE4R/FB7M8Q1QW/screenshot_2018-06-13_09.36.34.png
https://masterworks.slack.com/files/U87J9SE4R/FB7RW3LNB/screenshot_2018-06-13_09.36.46.png

**Comment by danielgolden** [comment]
### Security/Admin Screens Mockups:
- [Dashboard](https://invis.io/XVL9PUVFRUG)
- [View All Clients](https://invis.io/RDL9Q13W8YV)
- [Edit Client](https://invis.io/8HL9Q3RZR75)
- [View All Projects](https://invis.io/Q6L9Q6CCBH9)
- [Edit Project](https://invis.io/HUL9Q9LZGNV)
- [View All Users](https://invis.io/G5L9QAJAE4R)
- [Edit User](https://invis.io/D7L9QD13JVQ)
- [Edit Roles](https://invis.io/G2L9QDNPKED)
- [Edit Permission Sets](https://invis.io/S6L9QKB92UJ)
