### ISSUE TITLE
Many content section containers names `.o-user`

### ISSUE THREAD

**Issue by danielgolden** [Masterworks/Clarity-Components#11]
https://github.com/Masterworks/Clarity-Components/blob/d7aa78a0b5ae9d5165653649b41a08d36ea01889/clarity-html/edit-client.html#L175

There are many content section containers with a class of `o-user`, however the majority of them have nothing to do with the user. Why are these named this way?

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden As you informed many section don't have any relation with user so I changed the class name and replaced it with the utility one.

**Comment by danielgolden** [comment]
Thanks, Chitradeep!
