### ISSUE TITLE
Double nested inputs

### ISSUE THREAD

**Issue by danielgolden** [Masterworks/Clarity-Components#13]
Many select element containers have another instance of the same container as direct children. Why are these nested this way?

https://github.com/Masterworks/Clarity-Components/blob/bbc706960cedc5787f8c0bbf46bbff67bb056dda/clarity-html/edit-user.html#L172-L173

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden  Thanks for let me know the above, there is no use of same container inside direct children we can remove one easily without any problem, somehow it placed by mistake maybe, I removed it now.

**Comment by danielgolden** [comment]
Sounds good. Thanks, Chitradeep
