### ISSUE TITLE
More generic class name for `.o-rightPan`?

### ISSUE THREAD

**Issue by danielgolden** [Masterworks/Clarity-Components#14]
I'd like for this class name to be less generic so that I can be applied to "panels" that aren't just on the right. There are no positional styles applied to the class name so I believe this is just a semantics issue. I believe this is a class we should be able to use for any base/background panels like the existing ones and others like the one on edit projects screen which aren't located on the right but have the same visual styling otherwise.  Do you have any concerns or opinions about that?

https://github.com/Masterworks/Clarity-Components/blob/ba5ee0b3930e06476b76d87a147371f43ce2b74a/clarity-html/sass/base/_layout.scss#L24

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden  I have changed the class name, please check and let me know your view.

**Comment by danielgolden** [comment]
`o-shadowbox` works for me. Thanks, Chitradeep.
