### ISSUE TITLE
Dashboard tile width should not be influenced by content.

### ISSUE THREAD

**Issue by danielgolden** [Masterworks/Clarity-Components#15]
<img width="512" alt="screenshot_2018-07-10_11 39 50_1024" src="https://user-images.githubusercontent.com/812989/42530647-b6fe869c-844f-11e8-8d50-02ad0353c2c8.png">

When you reduce the length of the description inside of each tile, the width of the tile is reduced as well. These tiles should be the same width regardless of the amount of content they hold.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 
We have fixed this. This happens due to update of the custom grid.

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers please also make sure that these tiles have equal height.

**Comment by danielgolden** [comment]
Looks like this has been fixed 👍
