### ISSUE TITLE
Add New User

### ISSUE THREAD

**Issue by mdfrederick** [Masterworks/Clarity-Components#19]
@danielgolden For our Administration screens, on [List Users](https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/302709348) we have an "Add New User" button, but I do not see a screen for that.

Was it your intention that it be the same as Edit User?

Working off of that assumption we can re-use most of Edit User, but it may still be good to call it out and have it as it's own screen in Invision. What do you think?

**Comment by danielgolden** [comment]
Wow, you're right. That's a really good point, and I agree we should have a specific screen to clear up any ambiguity about the screen. I'll design it, add it to InVision and post it here when it's ready.

**Comment by danielgolden** [comment]
@mdfrederick I'm also realizing that we probably need something similar for "edit client", so I'm going to go ahead and add that to InVision too. Will will need the same for "New Role" and "New Permission Set" too?

**Comment by danielgolden** [comment]
✅ I've uploaded a [New User screen](https://invis.io/FHJBB3V7M9D#/311302778_New_User) to InVision (as well as a [New Client screen](https://invis.io/FHJBB3V7M9D#/311302789_New_Client)). When the "client" field for a new user is filled out, then the "Client Permissions" section should be displayed, but up until then it should be hidden.

**Comment by mdfrederick** [comment]
@danielgolden Yes, we need something for New Role and New Capability (Permission) Set as well, not a priority though. The pages actually already exist and function on the site using some default markup.

 I think "Selects Clients" can just be "Clients" or if you want consistency with the other items "Edit Clients". Selects is too specific, Clients will be used across the board (with other apps). Was it like that before and I missed it?

**New User Screen**

Let's tweak the workflow a bit. Instead of hidden, let's just omit Client Permissions. When you've saved (i.e. created) the User, we will redirect you to the "Edit User" screen. Keeps this simpler, reuses what's on the Edit screen.

We can change **Client(s)** to **Primary Client**, singular. Most new accounts from here on out should be actual employees of our Clients and they will only have access to one Client. This matches a requirement change we received at some point when we added a "Primary Client" field to the API.

**Comment by danielgolden** [comment]
> Selects is too specific, Clients will be used across the board (with other apps). Was it like that before and I missed it?

Not sure how that title made it this far because your comment makes a lot of sense. Guess we both missed it. This sounds good.

> Instead of hidden, let's just omit Client Permissions. When you've saved (i.e. created) the User, we will redirect you to the "Edit User" screen. Keeps this simpler, reuses what's on the Edit screen.

Cool, I like this a lot. I've also made the primary client label changes to the InVision screen.

**Comment by danielgolden** [comment]
Not sure what I did or thought I did, but I can't even see my changes. Updating them now...

**Comment by danielgolden** [comment]
Ok, now I've actually updated both.
- [Edit User](https://invis.io/FHJBB3V7M9D#/302709352_Edit_User)
- [New User](https://invis.io/FHJBB3V7M9D#/311302778_New_User)

I'm not sure what to do about the client permissions section on the edit user screen, because even though this example user doesn't have access to multiple clients, it's still possible that a user could have access to multiple clients, right? I'm afraid that If I remove the multiple clients listing and toggle functionality that it will be forgotten when implemented. 

Not sure if that makes sense, but in short, let me know if I should remove the remaining 3 clients from the client permissions section in the edit client screen.
