### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by mdfrederick** [Masterworks/Clarity-Components#2]
https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/298844997

**Comment by danielgolden** [comment]
A few points of feedback on the login screens for you @Chitradip-Capitalnumbers :

- [ ] When focused labels in inputs should be set in all-caps with 11% letter spacing.
- [ ] All type set in **Lato** currently should be replaced with **Source Sans Pro**. _(Lato was a font that I used early on in the design of the site but later switched away from. You perfectly followed the design here, so this is my fault for leaving lato in the design in this screen. I will change it in Figma now and I'll try to find any other instances of Lato in Figma as well to replace)_
- [ ] The reset password screen belongs on same gray color background as initial login screen.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 
Re :  All type set in Lato currently should be replaced with Source Sans Pro. (Lato was a font that I used early on in the design of the site but later switched away from. You perfectly followed the design here, so this is my fault for leaving lato in the design in this screen. I will change it in Figma now and I'll try to find any other instances of Lato in Figma as well to replace)
  ---> I have not used Lato in my updated works. But thanks for your information. I will keep this as a note.

**Comment by Chitradip-Capitalnumbers** [comment]
@mdfrederick 
I have completed the login screen. You can close this ticket.
