### ISSUE TITLE
Modal BEM issue

### ISSUE THREAD

**Issue by danielgolden** [Masterworks/Clarity-Components#24]
This issue applies to the following pages:
- forget-password-v2.html
- reset-password-v2.html
- email-sent-v2.html

There are a series of element and modifier classes for the modal that aren't elements of or modifiers of any block class. For example `.c-modal--active` should be a modifier of `.c-modal` and `.c-modal__container` should be an element of `.c-modal`, but `.c-modal` is no where to be found in this markup. It doesn't exist:

```html
<div class="c-container-wrap">
    <div class="c-modal--active">
        <div class="c-modal__container">
            <!-- content -->
        </div>
    </div>
</div>
```

The Block, Element, Modifier naming convention is the backbone of BEM, and it's critical that we follow it.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden ,
I have removed that modifier class. That has been overlooked by me.
Please check now.
