### ISSUE TITLE
CPP Screens Visual Issues

### ISSUE THREAD

**Issue by danielgolden** [Masterworks/Clarity-Components#27]
### cpp-enter-cost.html

- The Job number text and actual number should be vertically centered with the dotted separator to the right ([screenshot](https://user-images.githubusercontent.com/812989/44679724-bb622880-aa09-11e8-82fb-c1e3c063e001.png)).
- The cursor should become a pointer when hovered over the outlined buttons
- The "Submit Request" buttons shadows aren't behaving as they should. They should be the same as the blue version of this button except with the proper orange color.
- There is too much spacing between the table and the top of it's container ([screenshot](https://user-images.githubusercontent.com/812989/44679930-4cd19a80-aa0a-11e8-8d36-6b8cbae3c27c.png)).
- The font used for the number values in the table should be Fira Code. And set at 14px, not 16px.

### ccp-enter-cost-pop-1.html
There are many, many spacing issues in this. Please revisit the figma mockup and apply the proper spacing between the elements on this page.

### ccp-enter-cost-pop-2.html
There are also many, many spacing issues on this page. Please revisit the figma mockup and apply the proper spacing between the elements on this page using the measurements found in figma. There is too large a visual discrepancy between this page and the Figma mockup right now.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 

I have fixed above mentioned issue. Also completed the media page.
Please check and let me know your feedback.

Thanks
Chitradip

**Comment by danielgolden** [comment]
This is much better. Thank you, Chitradeep. As far as the Media page goes, the only issue I see is that the colors of the dollar value columns is incorrect.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 
I have updated the color.
Please review and let me know.

Thanks
Chitradip

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 
I have updated the font. 
Also, made progress on client report listing page. Please check and let me know your feedback.

Thanks
Chitradip
