### ISSUE TITLE
Administration Screens - Projects

### ISSUE THREAD

**Issue by mdfrederick** [Masterworks/Clarity-Components#7]
[Projects (Invision)](https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/302709347)

**Comment by Chitradip-Capitalnumbers** [comment]
Hello @mdfrederick,

@danielgolden has made this page, I have done some update respect to design. please check and let me know your feedback.

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers It's hard for me to tell track down your adjustments on this. I think they are all good to go, bu in the future please mentioned the issue number in your commit message so that it's logged here in the issue.
