### ISSUE TITLE
Administration Screens - Clients

### ISSUE THREAD

**Issue by mdfrederick** [Masterworks/Clarity-Components#8]
[Clients (Invision)](https://projects.invisionapp.com/share/UJJCGK5E6NX#/screens/302709346)

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden I have also worked on edit-client.html html page, please check once and let me share your view and advice.

**Comment by mdfrederick** [comment]
@danielgolden Closing this one. Reopen if you feel there is further work that needs done.

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers The "edit client" screen is good to go, but there is a minor issues with the "select client" screen:
- The click target for the menu button on the right side of each row in the table is too small. It's the same problem that I mentioned in #6 when I said that *"The click/tap target on on the table row menu buttons (the 3 vertical dots) needs to be larger than it currently is, these are easy to miss-click right now"*.

**Comment by Chitradip-Capitalnumbers** [comment]
@danielgolden 
I have updated this button. Please check and let me know the hit area is fine or you would like to increase that more than this.

Thanks
Chitradip

**Comment by danielgolden** [comment]
@Chitradip-Capitalnumbers This is a really good size. Thank you 👍🏽
